### ISSUE TITLE
caja integration

### ISSUE THREAD

**Issue by brokoli-mate** [Bajoja/indicator-kdeconnect#151]
Ubuntu mate 18.04. Caja does not have entry to send files. Adding script to scripts folders creates entry , but it does nothing.
Also browse device does not work.

**Comment by Bajoja** [comment]
[Have you try this one?](https://github.com/Bajoja/indicator-kdeconnect/tree/master/src/extensions/filemanager-python/caja)

**Comment by brokoli-mate** [comment]
It is already present in the /usr/share/caja-python/extensions
![kde-connect-folder](https://user-images.githubusercontent.com/28659655/49584480-5f396980-f953-11e8-9bef-ae8d19a6985a.png)

 but not visible in the caja preferences->extensions 
![kde-connect-list](https://user-images.githubusercontent.com/28659655/49584456-50eb4d80-f953-11e8-9bbf-229eb6608e35.png)

When i add it to scripts folder - action appears, and i get the "cross" , but nothing happens when i select file(s).

**Comment by FrancescoCappio** [comment]
Same problem in Arch Linux, I also have a stack Trace visible when starting Caja from Terminal:
```
Traceback (most recent call last):
  File "/usr/share/caja-python/extensions/kdeconnect-send-caja.py", line 9, in <module>
    gi.require_version('Caja', '3.0')
  File "/usr/lib/python2.7/site-packages/gi/__init__.py", line 121, in require_version
    (namespace, loaded_version))
ValueError: Namespace Caja is already loaded with version 2.0
```

**Comment by kescherCode** [comment]
I have found this while investigating this issue on Manjaro:

Using python version sys.version_info(major=2, minor=7, micro=17, releaselevel='final', serial=0)
```
  File "/usr/share/caja-python/extensions/kdeconnect-send.py", line 28
    self.dbus = Gio.DBusProxy.new_for_bus_sync(
                                              ^
IndentationError: unindent does not match any outer indentation level
```

Then again, is this a python 2 script at all?

**Comment by kescherCode** [comment]
After several reboots, the second error seems to have just randomly disappeared on my system.
