### ISSUE TITLE
Conflicting with Nautilus 3.20 Ubuntu 16.10

### ISSUE THREAD

**Issue by jvalenciag** [Bajoja/indicator-kdeconnect#46]
After install it I got this errors when trying to use nautilus (ctrl+p/ctrl+c)

```
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
/usr/share/nautilus-python/extensions/kdeconnect-send-nautilus.py:10: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Nautilus, GObject, Notify
```
```
CRITICAL **: nautilus_menu_provider_get_background_items: assertion 'NAUTILUS_IS_MENU_PROVIDER (provider)' failed
```
```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/kdeconnect-send-nautilus.py", line 60, in get_file_items
    if file.get_uri_scheme() != 'file' or file.is_directory() and os.path.isfile(file):
  File "/usr/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NautilusVFSFile found
```

**Comment by Bajoja** [comment]
@jvalenciag thanks for reporting, i figured out that affect Nautilus 3.18 and higher.

**Comment by Bajoja** [comment]
Eu descobri que o problema está na linha 32, o comando checkout está bloqueando Nautilus, eu tentei Popen e ainda bloqueando também.
Se alguem aqui entende de Python ajudar ficaria agradecido.
