### ISSUE TITLE
Sending SMS doesn't work

### ISSUE THREAD

**Issue by nagyt234** [Bajoja/indicator-kdeconnect#90]
indicator-kdeconnect finds my phone, but nothing happens by clicking on "Send SMS". If I start indicator-kdeconnect from command line I see, that there is a python error:
```
ntibor@centos1:~(2004)>/usr/bin/indicator-kdeconnect
** Message: KDEConnectManager.vala:33: KDE Connect daemon found
** Message: KDEConnectManager.vala:42: Devices file not creates
** Message: Device.vala:116: device : /modules/kdeconnect/devices/1419e7a6f249a3bc
** Message: InOut.vala:19: File path exist '/tmp/devices'

** Message: InOut.vala:33: Status found on file - Samsung Galaxy S4 Mini : 1419e7a6f249a3bc

Traceback (most recent call last):
  File "/usr/share/indicator-kdeconnect/Sms.py", line 23, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```
My environment: Ubuntu 16.04, Ssmsung S4 Mini Android 4.4.2

**Comment by nagyt234** [comment]
I found out that I have to install `gir1.2-notify-0.7`.
```
sudo apt install gir1.2-notify-0.7
```
